### ISSUE TITLE
simple example does not work on Windows

### ISSUE THREAD

**Issue by mbertucci47** [jarnosz/blopentype#2] opened 2023-06-23 19:10 UTC
On a Windows 10 machine with an up-to-date texlive, I cannot get the example file `blottest.tex` to work. Running `luatex blottest.tex` results in
```
This is LuaTeX, Version 1.17.0 (TeX Live 2023)
 restricted system commands enabled.
(./blottest.tex (c:/texlive/2023/texmf-dist/tex/luatex/blopentype/blot.tex
This is blopentype, v0.0.0 December 2022
(c:/texlive/2023/texmf-dist/tex/generic/luatex85/luatex85.sty)
(c:/texlive/2023/texmf-dist/tex/generic/yax/yax.tex
(c:/texlive/2023/texmf-dist/tex/generic/texapi/texapi.tex))
(c:/texlive/2023/texmf-dist/tex/generic/gates/gates.tex
(c:/texlive/2023/texmf-dist/tex/generic/texapi/texapi.tex))
(c:/texlive/2023/texmf-dist/tex/luatex/blopentype/blot-lua.tex)
(c:/texlive/2023/texmf-dist/tex/luatex/blopentype/blot-files.tex)
(c:/texlive/2023/texmf-dist/tex/luatex/blopentype/blot-fonts.tex...ive/2023/tex
mf-dist/tex/luatex/blopentype/blot-fonts.lua:257: attempt to index a nil value
(local 'fi')
stack traceback:
        ...ive/2023/texmf-dist/tex/luatex/blopentype/blot-fonts.lua:257: in upvalue 'e
xtract_font'
        ...ive/2023/texmf-dist/tex/luatex/blopentype/blot-fonts.lua:293: in upvalue 'c
heck_fonts'
        ...ive/2023/texmf-dist/tex/luatex/blopentype/blot-fonts.lua:289: in upvalue 'c
heck_fonts'
        ...ive/2023/texmf-dist/tex/luatex/blopentype/blot-fonts.lua:289: in local 'che
ck_fonts'
        ...ive/2023/texmf-dist/tex/luatex/blopentype/blot-fonts.lua:366: in main chunk

        [C]: in function 'dofile'
        [\directlua]:1: in main chunk.
\inputltcfile ...ua {dofile(kpse.find_file("#1"))}

l.1 \inputltcfile blot-fonts.lua

?
```
in the terminal. Hitting "Enter" through this prompt results in a bunch of errors. I thought perhaps this is due to blopentype not finding the font Palatino Linotype (which is installed), but I get the same issue with the file
```latex
\input blot
hello world!
\bye
```
I also tried with the latest version from Github but the same issue arises. Am I missing something obvious or is something wrong with the configuration for Windows?

**Comment by lodwicz** [comment] 2023-06-24 02:49
Hello! I just became aware of this and another issue on the Win10 platform; apparently, something got broken since at least LuaTeX 1.16 (I don't update that often, for LuaTeX is somewhat of a moving target), but I haven't had time to do some research. Just to make sure a couple of questions: 

1. From your log I see you are running the "native" Windows port, not the CygWin one. Correct?
2. Please, report if you have tried reverting to LuaTeX v1.15 or v1.16, to make sure that the problem depends on the LuaTeX engine side of things. 

Thank you!

**Comment by mbertucci47** [comment] 2023-06-24 03:16
It is "native" windows, though I just tried with WSL (ubuntu) which has luatex v1.15 and I get the same issue.

**Comment by lodwicz** [comment] 2023-06-24 06:21
I am unhappy to report that I could not reproduce the issue on my Win10 TeXLive LuaTeX 1.17 installation.

At this point, I suspect that some installation scripts may be interfering with `blopentype`'s functionality, but I need to run further tests.

FWIW, I have to state that I install LuaTeX manually, without distribution scripts, to keep my installation lean and clean.

I'll leave the issue open, with a warning, while I contact the TeXLive team to figure out what is wrong.

My apologies.

**Comment by lodwicz** [comment] 2023-06-24 12:46
To pursue my conjecture: you did install LuaTeX with the standard TeXLive manager system, correct?

**Comment by mbertucci47** [comment] 2023-06-24 13:20
Yes, with the standard texlive

**Comment by lodwicz** [comment] 2023-06-26 20:56
I am unhappy to report that I cannot reproduce the issue after installing TeXLive 2023 with the standard installer.

FWIW, this is the command line of my installation procedure:

    install-tl-windows -no-gui -no-doc-install -no-src-install -portable -paper letter -select-repository -non-admin

I had to run the TUI interface because my firewall prevents me from connecting to the automatic mirroring system, and then the GUI kept on crashing on me, because I didn't want to install TeXWorks. 

In the TUI interface I only selected the Plain and LuaTeX modules in addition to the Basic Setup, and the `blopentype` system worked as expected; unsurprisingly, `luaotfload.sty` required the LaTeX files `ltluatex.*` which had to be retrieved from elsewhere, but otherwise worked as expected.

My apologies.

**Comment by mbertucci47** [comment] 2023-06-26 21:06
Am I correct in thinking
```tex
\input blot
hello world!
\bye
```
should work no matter the system (fonts, etc.)? If so, that file produces an error on the texlive.net server, which should be a normal linux environment. You can try it at this link: https://texlive.net/run?%25%20!TEX%20luatex%0A%5Cinput%20blot%0Ahello%20world!%0A%5Cbye

**Comment by lodwicz** [comment] 2023-06-26 21:18
For your consolation, I found the very same error while trying to run `blopentype` on the CygWin64 port of LuaTeX, as per [this question on StackExchange](https://tex.stackexchange.com/questions/689243/cygwin-luatex-cannot-find-win10-system-fonts); so I believe that installation, along with the CGI, is broken. Perhaps you should file an issue on the `texlive.net` feedback system.

**Comment by lodwicz** [comment] 2023-06-26 21:31
To pursue this matter: which options did you choose to install TeXLive in your bitbox?

**Comment by mbertucci47** [comment] 2023-06-26 22:03
I didn't install from the command line, I just downloaded `install-tl-windows.exe` from https://tug.org/texlive/windows.html and followed the prompts. So to answer your question, whatever the defaults are with that exe file

**Comment by lodwicz** [comment] 2023-06-26 22:57
fair enough. thank you!

**Comment by davidcarlisle** [comment] 2023-06-27 08:56
I did not trace all the code but I think you are splitting the paths on semicolon

kpse returns  colon separated paths on posix  systems, even if semicolon are used in texmf.cnf

```
$ kpsexpand '$OPENTYPEFONTS'
.:{{}/home/davidc/.texlive2023/texmf-config,/home/davidc/.texlive2023/texmf-var,/home/davidc/texmf,!!/usr/local/texlive/texmf-local,!!/usr/local/texlive/2023/texmf-config,!!/usr/local/texlive/2023/texmf-var,!!/usr/local/texlive/2023/texmf-dist}/fonts/{opentype,truetype}//:/please/set/osfontdir/in/the/environment//

```

but here and elsewhere:

```
font_paths = str.explode(font_paths, ";+")
```

Note it is using the entire path list as a file

```
2023/texmf-dist/tex/luatex/blopentype/blot-fonts.lua:285: cannot open .:/home/d
avidc/.texlive2023/texmf-config/fonts/opentype/:/home/davidc/.texlive2023/texmf
-var/fonts/opentype/:/home/davidc/texmf/fonts/opentype/:/usr/local/texlive/texm
f-local/fonts/opentype/:/usr/local/texlive/2023/texmf-config/fonts/opentype/:/u
sr/local/texlive/2023/texmf-var/fonts/opentype/:/usr/local/texlive/2023/texmf-d
ist/fonts/opentype/:/home/davidc/.texlive2023/texmf-config/fonts/truetype/:/hom
e/davidc/.texlive2023/texmf-var/fonts/truetype/:/home/davidc/texmf/fonts/truety
pe/:/usr/local/texlive/texmf-local/fonts/truetype/:/usr/local/texlive/2023/texm
f-config/fonts/truetype/:/usr/local/texlive/2023/texmf-var/fonts/truetype/:/usr
/local/texlive/2023/texmf-dist/fonts/truetype/:/please/set/osfontdir/in/the/env
ironment/: No such file or directory

```

**Comment by davidcarlisle** [comment] 2023-06-27 09:18
> For your consolation, I found the very same error while trying to run `blopentype` on the CygWin64 port of LuaTeX, as per [this question on StackExchange](https://tex.stackexchange.com/questions/689243/cygwin-luatex-cannot-find-win10-system-fonts); so I believe that installation, along with the CGI, is broken. Perhaps you should file an issue on the `texlive.net` feedback system.

There is no issue at the texlive.net server. that's simply reporting the error that you get running the example in any linux texlive.

**Comment by davidcarlisle** [comment] 2023-06-27 11:36
If I make the changes below adding some support for : as well as ; separators, removing some calls to lower() as it was not finding files on case sensitive systems and adding a (probably wrong) catch for fi being null then the example at the top of this thread runs without error

```
*** /usr/local/texlive/2023/texmf-dist/tex/luatex/blopentype/blot-fonts.lua	Mon Jan  2 21:31:04 2023
--- ./blot-fonts.lua	Tue Jun 27 12:28:03 2023
***************
*** 128,134 ****
  
  -- Returns anything after the last dot, i.e. an extension.
  function lfs.extension (s)
!   return str.lower(str.match(s, "%.([^%.]*)$"))
  end
  
  local extensions = {
--- 128,135 ----
  
  -- Returns anything after the last dot, i.e. an extension.
  function lfs.extension (s)
! --  return str.lower(str.match(s, "%.([^%.]*)$"))
!   return str.match(s, "%.([^%.]*)$")
  end
  
  local extensions = {
***************
*** 175,181 ****
  -- directories happens with kpse). Also puts everything to lowercase.
  function lfs.smooth_file (f)
    f = str.gsub(f, "/.-/%.%./", "/")
!   f = str.gsub(f, "^%a", str.lower)
    return f
  end
  -- /lfs
--- 176,182 ----
  -- directories happens with kpse). Also puts everything to lowercase.
  function lfs.smooth_file (f)
    f = str.gsub(f, "/.-/%.%./", "/")
! --  f = str.gsub(f, "^%a", str.lower)
    return f
  end
  -- /lfs
***************
*** 220,226 ****
  for _, name in ipairs(settings.normal) do
    normal_names[name] = true
  end
! local local_path   = lfs.expand_var("$TEXMFHOME")
  local foundry_path = lfs.ensure_dir (local_path, "tex", "luatex", "foundry")
  -- local local_path   = lfs.expand_var("$TEXMFHOME")
  -- local foundry_path = lfs.ensure_dir (local_path, "fonts", "truetype", "public", "gfs")
--- 221,227 ----
  for _, name in ipairs(settings.normal) do
    normal_names[name] = true
  end
! local local_path   = lfs.expand_var("$TEXMFHOME"):gsub(":",";")
  local foundry_path = lfs.ensure_dir (local_path, "tex", "luatex", "foundry")
  -- local local_path   = lfs.expand_var("$TEXMFHOME")
  -- local foundry_path = lfs.ensure_dir (local_path, "fonts", "truetype", "public", "gfs")
***************
*** 251,256 ****
--- 252,262 ----
      subname = name
    else
      fi = fl.open(file)
+     -- blot-fonts.lua:257: attempt to index a nil value (local 'fi')
+      if not fi then
+         print("Can't open %s", file)
+         return
+ 	end
    end
    -- Getting the most precise information. Not necessarily the best
    -- solution, but since the user can modify the library, it's not so bad.
***************
*** 282,287 ****
--- 288,294 ----
  -- only those that arent in the libraries are considered.
  local fonts_done = {}
  local function check_fonts (rep, tb)
+   if lfs.isdir(rep) then
    for f in lfs.dir (rep) do
      if f ~= "." and f ~= ".." then
        f = str.gsub(rep, "/$", "") .. "/" .. f
***************
*** 308,313 ****
--- 315,321 ----
        end
      end
    end
+   end
  end
  
  -- Writes the library to an external file.
***************
*** 355,360 ****
--- 363,369 ----
  
  -- If there is no library, we create it.
  local font_paths = lfs.show_path("opentype fonts")
+ font_paths = str.gsub(font_paths, ":", ";")
  font_paths = str.gsub(font_paths, "\\", "/")
  font_paths = str.gsub(font_paths, "/+", "/")
  font_paths = str.gsub(font_paths, "!!", "")
***************
*** 398,403 ****
--- 407,415 ----
    LIB = str.gsub(LIB, ";%s*;", ";;")
    LIB = str.gsub(LIB, ";+", ";")
    LIB = str.gsub(LIB, "^;", "")
+   LIB = str.gsub(LIB, ":%s*:", "::")
+   LIB = str.gsub(LIB, ":+", ":")
+   LIB = str.gsub(LIB, "^:", "")
    LIB = str.gsub(LIB, "%s+", " ")
  
    LIB = lp.match(explode_semicolon, LIB)
```

**Comment by lodwicz** [comment] 2023-06-27 19:19
@davidcarlisle I was already narrowing it down to a mismatch in the *nix paths, so your patch comes in just in time. 

I've just applied the patch, and the error is gone on CygWin64; I'll test it in my old Linux32 box, and study the fixes before posting an update: thank you!

**Comment by lodwicz** [comment] 2023-06-27 19:35
@davidcarlisle Quick question: the query on `kpathsea` for known file types should or not include the extension? I am getting different results for fonts:

```
jlrn@pc-19002 /cygdrive/c/Users/jlrivera/documents/256/texmf/tex/luatex
$ kpsewhich -show-path=mf
.:/home/jlrn/.config/texmf/metafont//:/home/jlrn/.cache/texmf/metafont//:/cygdrive/c/Users/jlrivera/documents/256/texmf/metafont//:!!/cygdrive/c/Users/jlrivera/documents/pdflatex/metafont//:!!/etc/texmf/metafont//:!!/var/lib/texmf/metafont//:!!/usr/share/texmf-dist/metafont//:/home/jlrn/.config/texmf/fonts/source//:/home/jlrn/.cache/texmf/fonts/source//:/cygdrive/c/Users/jlrivera/documents/256/texmf/fonts/source//:!!/cygdrive/c/Users/jlrivera/documents/pdflatex/fonts/source//:!!/etc/texmf/fonts/source//:!!/var/lib/texmf/fonts/source//:!!/usr/share/texmf-dist/fonts/source//:/home/jlrn/.cache/texmf/fonts/source//

jlrn@pc-19002 /cygdrive/c/Users/jlrivera/documents/256/texmf/tex/luatex
$ kpsewhich -show-path=tex
.:/home/jlrn/.config/texmf/tex/kpsewhich//:/home/jlrn/.cache/texmf/tex/kpsewhich//:/cygdrive/c/Users/jlrivera/documents/256/texmf/tex/kpsewhich//:!!/cygdrive/c/Users/jlrivera/documents/pdflatex/tex/kpsewhich//:!!/etc/texmf/tex/kpsewhich//:!!/var/lib/texmf/tex/kpsewhich//:!!/usr/share/texmf-dist/tex/kpsewhich//:/home/jlrn/.config/texmf/tex/generic//:/home/jlrn/.cache/texmf/tex/generic//:/cygdrive/c/Users/jlrivera/documents/256/texmf/tex/generic//:!!/cygdrive/c/Users/jlrivera/documents/pdflatex/tex/generic//:!!/etc/texmf/tex/generic//:!!/var/lib/texmf/tex/generic//:!!/usr/share/texmf-dist/tex/generic//:/home/jlrn/.config/texmf/tex/latex//:/home/jlrn/.cache/texmf/tex/latex//:/cygdrive/c/Users/jlrivera/documents/256/texmf/tex/latex//:!!/cygdrive/c/Users/jlrivera/documents/pdflatex/tex/latex//:!!/etc/texmf/tex/latex//:!!/var/lib/texmf/tex/latex//:!!/usr/share/texmf-dist/tex/latex//:/home/jlrn/.config/texmf/tex///:/home/jlrn/.cache/texmf/tex///:/cygdrive/c/Users/jlrivera/documents/256/texmf/tex///:!!/cygdrive/c/Users/jlrivera/documents/pdflatex/tex///:!!/etc/texmf/tex///:!!/var/lib/texmf/tex///:!!/usr/share/texmf-dist/tex///

jlrn@pc-19002 /cygdrive/c/Users/jlrivera/documents/256/texmf/tex/luatex
$ kpsewhich -show-path=pfb
warning: kpsewhich: Ignoring unknown file type `pfb'.
warning: kpsewhich: Unknown file type, cannot show path: pfb.

jlrn@pc-19002 /cygdrive/c/Users/jlrivera/documents/256/texmf/tex/luatex
$ kpsewhich -show-path=.pfb
.:/home/jlrn/.config/texmf/fonts/type1//:/home/jlrn/.cache/texmf/fonts/type1//:/cygdrive/c/Users/jlrivera/documents/256/texmf/fonts/type1//:!!/cygdrive/c/Users/jlrivera/documents/pdflatex/fonts/type1//:!!/etc/texmf/fonts/type1//:!!/var/lib/texmf/fonts/type1//:!!/usr/share/texmf-dist/fonts/type1//:/cygdrive/c/windows/fonts//

jlrn@pc-19002 /cygdrive/c/Users/jlrivera/documents/256/texmf/tex/luatex
$ kpsewhich -show-path=ttf
warning: kpsewhich: Ignoring unknown file type `ttf'.
warning: kpsewhich: Unknown file type, cannot show path: ttf.

jlrn@pc-19002 /cygdrive/c/Users/jlrivera/documents/256/texmf/tex/luatex
$ kpsewhich -show-path=.ttf
.:/home/jlrn/.config/texmf/fonts/truetype//:/home/jlrn/.cache/texmf/fonts/truetype//:/cygdrive/c/Users/jlrivera/documents/256/texmf/fonts/truetype//:!!/cygdrive/c/Users/jlrivera/documents/pdflatex/fonts/truetype//:!!/etc/texmf/fonts/truetype//:!!/var/lib/texmf/fonts/truetype//:!!/usr/share/texmf-dist/fonts/truetype//:/home/jlrn/.config/texmf/fonts/opentype//:/home/jlrn/.cache/texmf/fonts/opentype//:/cygdrive/c/Users/jlrivera/documents/256/texmf/fonts/opentype//:!!/cygdrive/c/Users/jlrivera/documents/pdflatex/fonts/opentype//:!!/etc/texmf/fonts/opentype//:!!/var/lib/texmf/fonts/opentype//:!!/usr/share/texmf-dist/fonts/opentype//:/cygdrive/c/windows/fonts//
```

Why is the dot in the scalable font extension relevant?

**Comment by davidcarlisle** [comment] 2023-06-27 19:37
note I'm fairly sure the patch is wrong in parts, but was enough to show the direction for a fix.

it was failing on mixed case names, so I removed some uses of lower() but I didn't check if elsewhere you rely on lowercase eg checking file extensions like `.TTF` 

I just searched for `;` handling and pushed in some `:` but this almost certainly breaks `c:\windows\fonts` and other drive letter colon, so it may need a more careful Lua pattern to match this.

```
+      if not fi then
+         print("Can't open %s", file)
+         return
+ 	end
```

is weak, if it should be an error it should error not simply `print()` but better would be to not reach that ( I had 2 mixed case filenames that reached here) but I couldn't follow the logic of what was supposed to happe so just bail out with `return`

**Comment by lodwicz** [comment] 2023-06-27 19:39
> note I'm fairly sure the patch is wrong in parts, but was enough to show the direction for a fix.
> 
> it was failing on mixed case names, so I removed some uses of lower() but I didn't check if elsewhere you rely on lowercase eg checking file extensions like `.TTF`
> 
> I just searched for `;` handling and pushed in some `:` but this almost certainly breaks `c:\windows\fonts` and other drive letter colon, so it may need a more careful Lua pattern to match this.
> 
> ```
> +      if not fi then
> +         print("Can't open %s", file)
> +         return
> + 	end
> ```
> 
> is weak, if it should be an error it should error not simply `print()` but better would be to not reach that ( I had 2 mixed case filenames that reached here) but I couldn't follow the logic of what was supposed to happe so just bail out with `return`

copy that...

**Comment by davidcarlisle** [comment] 2023-06-27 19:41
`kpsewhich -show-path=mf`

the argument is not a file extension it is a symbolic name for a kpse path

see

`kpsewhich --help-formats`


which makes

```
Recognized Kpathsea format names and their (abbreviations) and suffixes:
gf: gf  [variables: GFFONTS GLYPHFONTS TEXFONTS]
  [original path (from texmf.cnf) = $TEXMFDOTDIR:$TEXMF/fonts/gf/$MAKETEX_MODE//]
pk: pk  [variables: PKFONTS TEXPKS GLYPHFONTS TEXFONTS]
  [original path (from texmf.cnf) = $TEXMFDOTDIR:{$TEXMF/fonts,$VARTEXFONTS}/pk/{$MAKETEX_MODE,modeless}//]
.....
```

**Comment by lodwicz** [comment] 2023-06-27 19:48
> `kpsewhich -show-path=mf`
> 
> the argument is not a file extension it is a symbolic name for a kpse path
> 
> see
> 
> `kpsewhich --help-formats`
> 
> which makes
> 
> ```
> Recognized Kpathsea format names and their (abbreviations) and suffixes:
> gf: gf  [variables: GFFONTS GLYPHFONTS TEXFONTS]
>   [original path (from texmf.cnf) = $TEXMFDOTDIR:$TEXMF/fonts/gf/$MAKETEX_MODE//]
> pk: pk  [variables: PKFONTS TEXPKS GLYPHFONTS TEXFONTS]
>   [original path (from texmf.cnf) = $TEXMFDOTDIR:{$TEXMF/fonts,$VARTEXFONTS}/pk/{$MAKETEX_MODE,modeless}//]
> .....
> ```

clear enough! thank you!

**Comment by lodwicz** [comment] 2023-06-27 21:57
@mbertucci47 Please try the patched version available in the win-nix branch.

**Comment by mbertucci47** [comment] 2023-06-27 22:10
Seems to work now! Just a note: the first time I ran `luatex test.tex` on
```tex
\input blot
hello world!
\bye
```
the terminal produced some messages about fonts that I don't understand:
```
This is LuaTeX, Version 1.17.0 (TeX Live 2023)
 restricted system commands enabled.
(./test.tex (./blot.tex This is blopentype, v0.0.0 December 2022
(c:/texlive/2023/texmf-dist/tex/generic/luatex85/luatex85.sty)
(c:/texlive/2023/texmf-dist/tex/generic/yax/yax.tex
(c:/texlive/2023/texmf-dist/tex/generic/texapi/texapi.tex))
(c:/texlive/2023/texmf-dist/tex/generic/gates/gates.tex
(c:/texlive/2023/texmf-dist/tex/generic/texapi/texapi.tex)) (./blot-lua.tex)
(./blot-files.tex) (./blot-fonts.texCan't open %s       /texlive/2023/texmf-dist/fonts/opentype/public/helmholtz-ellis-ji-notation/HEJI2Text.otf
Can't open %s   /texlive/2023/texmf-dist/fonts/truetype/google/noto-emoji/NotoColorEmoji.ttf
)) [1{c:/texlive/2023/texmf-var/fonts/map/p
dftex/updmap/pdftex.map}])<c:/texlive/2023/texmf-dist/fonts/type1/public/amsfon
ts/cm/cmr10.pfb>
Output written on test.pdf (1 page, 11678 bytes).
Transcript written on test.log.
```
Subsequent runs did not produce these messages.

**Comment by davidcarlisle** [comment] 2023-06-27 22:18
@mbertucci47 

>  helmholtz-ellis-ji-notation/HEJI2Text.otf

yes they were the ones I got too

>  ( I had 2 mixed case filenames that reached here)

The code won't load that for some reason

> Subsequent runs did not produce these messages.

it builds the font index on the first run only. Those fonts get skipped

**Comment by lodwicz** [comment] 2023-06-27 22:27
I don't have those fonts, so my system does not report anything wrong; but I will try to check it again. thanks!

**Comment by lodwicz** [comment] 2023-06-28 02:27
HEJI2Text.otf and NotoColorEmoji.ttf seem to be highly unusual fonts: windows reports them as unusable, and I could not open them with FontForge; I'll delve into them whenever I have more spare time.

**Comment by lodwicz** [comment] 2023-06-28 02:54
@mbertucci47 Please rename the `readable.txt` font database at `$TEXMFHOME/tex/luatex/foundry`, and rerun the test to regenerate the database after updating `blot-fonts.lua` with the new push in the `win-nix` branch: your database should be bigger: more fonts are recognized and stored, with slightly better informative warnings.

**Comment by lodwicz** [comment] 2023-06-29 19:06
tested on my Linux32 bitbox; ready to distribute.

**Comment by mbertucci47** [comment] 2023-06-30 15:24
Sorry I just tested the new version in the main branch and am getting the same error I got initially,
```tex
This is LuaTeX, Version 1.17.0 (TeX Live 2023)
 restricted system commands enabled.
(./blottest.tex (./blot.tex This is blopentype, v0.0.2 June 2023
(c:/texlive/2023/texmf-dist/tex/generic/luatex85/luatex85.sty)
(c:/texlive/2023/texmf-dist/tex/generic/yax/yax.tex
(c:/texlive/2023/texmf-dist/tex/generic/texapi/texapi.tex))
(c:/texlive/2023/texmf-dist/tex/generic/gates/gates.tex
(c:/texlive/2023/texmf-dist/tex/generic/texapi/texapi.tex)) (./blot-lua.tex)
(./blot-files.tex) (./blot-fonts.tex
Cannot open file        /texlive/2023/texmf-dist/fonts/opentype/public/helmholtz-ellis-ji-notation/HEJI2Text.otf
./blot-fonts.lua:131: bad argument #1 to 'l
ower' (string expected, got nil)
stack traceback:
        [C]: in function 'string.lower'
        ./blot-fonts.lua:131: in field 'extension'
        ./blot-fonts.lua:299: in upvalue 'check_fonts'
        ./blot-fonts.lua:297: in upvalue 'check_fonts'
        ./blot-fonts.lua:297: in local 'check_fonts'
        ./blot-fonts.lua:376: in main chunk
        [C]: in function 'dofile'
        [\directlua]:1: in main chunk.
\inputltcfile ...ua {dofile(kpse.find_file("#1"))}

l.1 \inputltcfile blot-fonts.lua

?
```

**Comment by davidcarlisle** [comment] 2023-06-30 19:22
that's the extensionless file

    /usr/local/texlive/2023/texmf-dist/fonts/opentype/public/lilyglyphs/FONTLOG

**Comment by davidcarlisle** [comment] 2023-06-30 19:29
@mbertucci47  you could add `or ""` on line 131

```
131c132
<   return str.lower(str.match(s, "%.([^%.]*)$"))
---
>   return str.lower(str.match(s, "%.([^%.]*)$") or "")
```

**Comment by mbertucci47** [comment] 2023-06-30 20:49
@davidcarlisle Yes that fixes it

**Comment by lodwicz** [comment] 2023-09-02 20:05
on leave for the summer: just committed. thank you, with my apologies.

> @mbertucci47 you could add `or ""` on line 131
> 
> ```
> 131c132
> <   return str.lower(str.match(s, "%.([^%.]*)$"))
> ---
> >   return str.lower(str.match(s, "%.([^%.]*)$") or "")
> ```

**Closed as completed by lodwicz** 2023-09-02 20:05 UTC
